apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-test-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/edwin-straub-org/dxp.git
    targetRevision: main
    path: environments/local/test/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: dxp-test-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
